### PR TITLE
added GPU Cost to a column in allocationReport.js

### LINKED ISSUE #7: add GPU metric  in UI
I'm always frustrated when Opencost svc (9003) see correctly GPU metrics, and Opencost UI is not displaying them.

The solution I woulk like would be to add GPU in UI 

Moving from OpenSource to community Kubecost

### PR DESCRIPTION
**Pull request by cchildress-gsu**
## What does this PR change?
Adds a column to the main page for GPU cost between CPU and RAM

## Does this PR relate to any other PRs?
No

## How will this PR impact users?
Adds a column for GPU

## Does this PR address any GitHub or Zendesk issues?
* Closes #7 

## How was this PR tested?
Ran on local opencost instance with GPU costs appropriately reported. 

## Does this PR require changes to documentation?
no

## Have you labeled this PR and its corresponding Issue as "next release" if it should be part of the next OpenCost release? If not, why not?
Not sure if GPU cost needs to be conditional, nor if this is the particular fix.

### CODE REVIEW

**Comment by lmello** [comment]
@cchildress-gsu  can you sign the DCO ?

**Comment by cchildress-gsu** [comment]
@lmello I added the required signoff.

**Comment by mattray** [comment]
@cchildress-gsu do you have a screenshot? The patch looks fine to me, just want to see it in action.

**Review by lmello — APPROVED** [review]
@cchildress-gsu Thank you for your contribution

**Pull request merged**
